/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyscoresImport } from './routes/myscores'
import { Route as HiscoresImport } from './routes/hiscores'
import { Route as IndexImport } from './routes/index'
import { Route as GameSessionidImport } from './routes/game.$session_id'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const MyscoresRoute = MyscoresImport.update({
  path: '/myscores',
  getParentRoute: () => rootRoute,
} as any)

const HiscoresRoute = HiscoresImport.update({
  path: '/hiscores',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameSessionidRoute = GameSessionidImport.update({
  path: '/game/$session_id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/game.$session_id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hiscores': {
      id: '/hiscores'
      path: '/hiscores'
      fullPath: '/hiscores'
      preLoaderRoute: typeof HiscoresImport
      parentRoute: typeof rootRoute
    }
    '/myscores': {
      id: '/myscores'
      path: '/myscores'
      fullPath: '/myscores'
      preLoaderRoute: typeof MyscoresImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/$session_id': {
      id: '/game/$session_id'
      path: '/game/$session_id'
      fullPath: '/game/$session_id'
      preLoaderRoute: typeof GameSessionidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  HiscoresRoute,
  MyscoresRoute,
  AboutLazyRoute,
  GameSessionidRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hiscores",
        "/myscores",
        "/about",
        "/game/$session_id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hiscores": {
      "filePath": "hiscores.tsx"
    },
    "/myscores": {
      "filePath": "myscores.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/game/$session_id": {
      "filePath": "game.$session_id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
